[CPUFREQ] EXYNOS: Fix compilation issue introduced during 3.4 merge
Commit a855039ee4b8 ("ARM: EXYNOS: change the prefix S5P_ to EXYNOS4_ for clock")
modifies some of the macro definitions which are still used in CPUFREQ driver.

This fixes similar compilation errors in exynos4210-cpufreq.c.

drivers/cpufreq/exynos4210-cpufreq.c: In function ‘exynos4210_set_clkdiv’:
drivers/cpufreq/exynos4210-cpufreq.c:124:2: error: ‘S5P_CLKDIV_CPU’ undeclared (first use in this function)

Cc: Kukjin Kim <kgene.kim@samsung.com>
Cc: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Tushar Behera <tushar.behera@linaro.org>