warnings in arch/arm/mach-imx/Kconfig
Without this patch, building rand-vOpR4V0 results in:

WARNING: vmlinux.o(.text+0x5bd4cc): Section mismatch in reference from the function dw_mci_pltfm_probe() to the function .devinit.text:dw_mci_probe()
The function dw_mci_pltfm_probe() references
the function __devinit dw_mci_probe().
This is often because dw_mci_pltfm_probe lacks a __devinit
annotation or the annotation of dw_mci_probe is wrong.

arch/arm/mach-imx/built-in.o: In function `v7_cpu_resume':
/home/arnd/linux-arm/arch/arm/mach-imx/head-v7.S:104: undefined reference to `cpu_resume'
make[1]: *** [vmlinux] Error 1
make: *** [sub-make] Error 2

Generated by script, please check manually

Signed-off-by: Arnd Bergmann <arnd@arndb.de>