video: mx2_camera: Fix build error due to the lack of 'pixfmt' definition
commit d509835 ([media] media: mx2_camera: Fix mbus format handling) caused
the following build error:

drivers/media/video/mx2_camera.c:1032:42: error: 'pixfmt' undeclared (first use in this function)
make[4]: *** [drivers/media/video/mx2_camera.o] Error 1

Fix this build error by providing a 'pixfmt' definition.

Signed-off-by: Fabio Estevam <fabio.estevam@freescale.com>