i2c: piix4: add missing include <linux/slab.h>
Building this driver on ARM produces a compiler warning

drivers/i2c/busses/i2c-piix4.c: In function 'piix4_add_adapter':
drivers/i2c/busses/i2c-piix4.c:551:2: error: implicit declaration of function 'kzalloc' [-Werror=implicit-function-declaration]
drivers/i2c/busses/i2c-piix4.c:551:7: warning: assignment makes pointer from integer without a cast [enabled by default]
drivers/i2c/busses/i2c-piix4.c:561:11: warning: assignment makes pointer from integer without a cast [enabled by default]
drivers/i2c/busses/i2c-piix4.c:563:3: error: implicit declaration of function 'kfree' [-Werror=implicit-function-declaration]

We must make sure that linux/slab.h is included explicitly
to avoid this.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>