ath6kl: Fix compile error because of deletion of htc_hif.h
htc_hif.h file no longer exists and it results in a build failure in
ath6kl driver.

It fixes following error.

drivers/net/wireless/ath/ath6kl/sdio.c:26:21: fatal error: htc_hif.h: No
such file or directory

Signed-off-by: Sangwook Lee <sangwook.lee@linaro.org>