warnings in drivers/media/radio/Kconfig
Without this patch, building rand-HBPwtoc results in:

WARNING: vmlinux.o(.text+0x294608): Section mismatch in reference from the function dw_mci_probe() to the function .init.text:dw_mci_init_slot()
The function dw_mci_probe() references
the function __init dw_mci_init_slot().
This is often because dw_mci_probe lacks a __init
annotation or the annotation of dw_mci_init_slot is wrong.

drivers/built-in.o: In function `usb_shark_disconnect':
/home/arnd/linux-arm/drivers/media/radio/radio-shark2.c:232: undefined reference to `led_classdev_unregister'
/home/arnd/linux-arm/drivers/media/radio/radio-shark2.c:232: undefined reference to `led_classdev_unregister'
drivers/built-in.o: In function `usb_shark_probe':
/home/arnd/linux-arm/drivers/media/radio/radio-shark2.c:309: undefined reference to `led_classdev_register'
make[1]: *** [vmlinux] Error 1
make: *** [sub-make] Error 2

Generated by script, please check manually

Signed-off-by: Arnd Bergmann <arnd@arndb.de>