pwm: Fix compilation error when CONFIG_PWM is not defined
As per Documentation/pwm.txt, PWM_LOOKUP and pwm_add_table are used in
board support files to add PWM chip entries. Currently these
definitions are protected within CONFIG_PWM macro in
include/linux/pwm.h.

Otherwise, we have to add ifdef's in machine file to fix following
compilation error.

error: array type has incomplete element type
error: implicit declaration of function ‘PWM_LOOKUP’ [-Werror=implicit-function-declaration]
error: implicit declaration of function ‘pwm_add_table’ [-Werror=implicit-function-declaration]
error: bit-field ‘<anonymous>’ width not an integer constant

Reported-by: Sachin Kamat <sachin.kamat@linaro.org>
Signed-off-by: Tushar Behera <tushar.behera@linaro.org>