[ARM] warnings in drivers/gpu/drm/udl/Kconfig
Without this patch, building rand-sA44iE1 results in:

WARNING: vmlinux.o(.text+0x287bc0): Section mismatch in reference from the function dw_mci_pltfm_probe() to the function .devinit.text:dw_mci_probe()
The function dw_mci_pltfm_probe() references
the function __devinit dw_mci_probe().
This is often because dw_mci_pltfm_probe lacks a __devinit
annotation or the annotation of dw_mci_probe is wrong.

drivers/built-in.o: In function `usb_string':
/home/arnd/linux-arm/drivers/usb/core/message.c:835: undefined reference to `utf16s_to_utf8s'
make[1]: *** [vmlinux] Error 1
make: *** [sub-make] Error 2

Generated by script, please check manually

Signed-off-by: Arnd Bergmann <arnd@arndb.de>